name: My Cool Workflow

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    # Specify the environment that this job is going to run on (OS)
    runs-on: ubuntu-latest

    steps:
      - name: Get code from the repository
        uses: actions/checkout@v4
        
      - name: Build application
        run: echo "Building the app..."

      - name: Run tests
        run: |
          echo "Testing the app..."
          echo "All the tests passed!"

      - name: Deploy app
        run: |
          echo "Deploying the app..."
          echo "Packaged files:"
          ls
    
